# Generated by Django 4.2 on 2023-04-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oppgavetekst', models.CharField(max_length=200)),
                ('ferdig', models.BooleanField(default=False)),
            ],
        ),
    ]
