# Generated by Django 4.2 on 2023-04-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_todo_dato_fullført'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='dato_fullført',
        ),
    ]
